In [4]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import numpy as np
import holidays
import datetime
%matplotlib inline

2 Cells below is relevant only when activating on cloud / Linux machine.
Since on Windows  google.colab not working


from google.colab import files
uploaded = files.upload()

import io
DataFrame = pd.read_csv(io.BytesIO(uploaded['Crimes_-_2020.csv']))
DataFrame

Update csv data bease:
https://drive.google.com/file/d/1s5lavM_C9aLsgdFzUmXOfbh_XvSxl-G4/view?usp=sharing

In [5]:
DataFrame = pd.read_csv("Crimes_-_2019_to_Present.csv")

In [6]:
DataFrame.columns

Index(['Unnamed: 0', 'ID', 'Case Number', 'Date', 'Block', 'IUCR',
       'Primary Type', 'Description', 'Location Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code',
       'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude',
       'Longitude', 'Location'],
      dtype='object')

In [7]:
Sunrise = pd.read_csv('sunrise-chicago.csv')


In [8]:
# Add converted columns
Sunrise['dtsunset']=Sunrise.apply(lambda x: datetime.datetime.combine(pd.to_datetime(x['date']), pd.to_datetime(x['sunset']).time()), axis=1)
Sunrise['dtsunrise']=Sunrise.apply(lambda x: datetime.datetime.combine(pd.to_datetime(x['date']), pd.to_datetime(x['sunrise']).time()), axis=1)



In [9]:
# a constant defining the time between sunset and darkness
delta_sunset = datetime.timedelta(0,3600)
#TODO: check exact delta, set another constant for sunrise time



In [10]:
# Accepts datetime in string, returns boolean if it's in night time
def is_dark(datecol) :
  d = pd.to_datetime(datecol)
  row = Sunrise.loc[Sunrise['date']==d.strftime("%Y-%m-%d")]
  return d < row['dtsunrise'].item() or d > (row['dtsunset'].item() + delta_sunset)

# Add IsDark colunm to DataFrame
# for tests, uncomment the next line and comment the line after it
#DataFrame = DataFrame.head()
#DataFrame['IsDark']=DataFrame.apply(lambda x: is_dark(x['Date']) ,axis=1)

Based on link below, we shall use FBI code instead of IUCR .
http://gis.chicagopolice.org/clearmap_crime_sums/crime_types.html#N04A
For example :

> **FBI code** - Homicide 1st & 2nd Degree - 01A

> **IUCR** 
*  0110 HOMICIDE FIRST DEGREE MURDER
*  0130 HOMICIDE SECOND DEGREE MURDER

> **FBI code** - Nonvoluntary Manslaughter - 01B

> **IUCR** 
*    0141 HOMICIDE INVOLUNTARY MANSLAUGHTER
*    0142 HOMICIDE RECKLESS HOMICIDE

In [11]:
DataFrame

Unnamed: 0        ID Case Number                    Date  \
0              136  11630494    JC194484  03/19/2019 04:30:00 PM   
1              148  11630497    JC193763  03/19/2019 09:00:00 AM   
2              258  11635490    JC199812  02/11/2019 05:50:00 PM   
3              279  11634522    JC199087  03/20/2019 07:00:00 PM   
4              286  11632505    JC196841  03/20/2019 01:00:00 AM   
...            ...       ...         ...                     ...   
428907     7217672  11700037    JC278815  05/26/2019 12:10:00 AM   
428908     7217673  11703089    JC282400  05/26/2019 11:29:00 AM   
428909     7217674  11700926    JC279725  05/26/2019 05:13:00 PM   
428910     7217675     24560    JC279072  05/26/2019 06:48:00 AM   
428911     7217678     24559    JC278908  05/26/2019 02:11:00 AM   

                        Block  IUCR        Primary Type  \
0          040XX W FOSTER AVE  0890               THEFT   
1             015XX W 17TH ST  0820               THEFT   
2       020XX N spaulding ave  0820               THEFT   
3          022XX W PRATT BLVD  1320     CRIMINAL DAMAGE   
4            013XX W HOOD AVE  0810               THEFT   
...                       ...   ...                 ...   
428907    046XX W MC LEAN AVE  0460             BATTERY   
428908       021XX W GRACE ST  1130  DECEPTIVE PRACTICE   
428909   036XX W DOUGLAS BLVD  2825       OTHER OFFENSE   
428910    013XX W HASTINGS ST  0110            HOMICIDE   
428911    013XX W HASTINGS ST  0110            HOMICIDE   

                     Description           Location Description  Arrest  ...  \
0                  FROM BUILDING             GROCERY FOOD STORE   False  ...   
1                 $500 AND UNDER                         STREET   False  ...   
2                 $500 AND UNDER  RESIDENTIAL YARD (FRONT/BACK)   False  ...   
3                     TO VEHICLE                         STREET   False  ...   
4                      OVER $500                          OTHER   False  ...   
...                          ...                            ...     ...  ...   
428907                    SIMPLE                      RESIDENCE    True  ...   
428908  FRAUD OR CONFIDENCE GAME                          OTHER   False  ...   
428909   HARASSMENT BY TELEPHONE                      APARTMENT   False  ...   
428910       FIRST DEGREE MURDER                CHA PARKING LOT    True  ...   
428911       FIRST DEGREE MURDER                         STREET   False  ...   

        Ward  Community Area  FBI Code  X Coordinate  Y Coordinate  Year  \
0       39.0            13.0        06           NaN           NaN  2019   
1       25.0            31.0        06           NaN           NaN  2019   
2       26.0            22.0        06           NaN           NaN  2019   
3       50.0             2.0        14           NaN           NaN  2019   
4       48.0            77.0        06           NaN           NaN  2019   
...      ...             ...       ...           ...           ...   ...   
428907  36.0            19.0       08B     1145043.0     1913219.0  2019   
428908  47.0             5.0        11           NaN           NaN  2019   
428909  24.0            29.0        26     1152126.0     1893208.0  2019   
428910  25.0            28.0       01A     1167752.0     1893853.0  2019   
428911  25.0            28.0       01A     1167746.0     1893853.0  2019   

                    Updated On   Latitude  Longitude  \
0       03/26/2019 04:15:20 PM        NaN        NaN   
1       03/26/2019 04:15:20 PM        NaN        NaN   
2       03/27/2019 04:10:11 PM        NaN        NaN   
3       03/27/2019 04:10:11 PM        NaN        NaN   
4       03/27/2019 04:10:11 PM        NaN        NaN   
...                        ...        ...        ...   
428907  06/30/2019 03:56:27 PM  41.917879 -87.742535   
428908  06/02/2019 04:09:42 PM        NaN        NaN   
428909  06/30/2019 03:56:27 PM  41.862830 -87.717040   
428910  06/20/2020 03:48:45 PM  41.864278 -87.65

In [12]:
DataFrame.columns

Index(['Unnamed: 0', 'ID', 'Case Number', 'Date', 'Block', 'IUCR',
       'Primary Type', 'Description', 'Location Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code',
       'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude',
       'Longitude', 'Location'],
      dtype='object')

**dt0 - Seasons numeric**

*   4- Fall   - Lowest crime rate
*   3- Summer - Highest crime rate

*   2- Spring
*   1- Winter

**dt1 - Weekday numeric**
 The day of the week with Monday=0, Sunday=6 
 
**dt2 - Weekday string** 

*  Sunday - Highest rate crimes
*  Tuesday - Lowest rate crimes


   
    


In [13]:
dtTemp = DataFrame.copy()

In [14]:
dtTemp=dtTemp.drop(['Block' , 'IUCR' , 'Primary Type' , 'Description' , 'Location Description' , 'Location'], axis=1 )
dtTemp

Unnamed: 0        ID Case Number                    Date  Arrest  \
0              136  11630494    JC194484  03/19/2019 04:30:00 PM   False   
1              148  11630497    JC193763  03/19/2019 09:00:00 AM   False   
2              258  11635490    JC199812  02/11/2019 05:50:00 PM   False   
3              279  11634522    JC199087  03/20/2019 07:00:00 PM   False   
4              286  11632505    JC196841  03/20/2019 01:00:00 AM   False   
...            ...       ...         ...                     ...     ...   
428907     7217672  11700037    JC278815  05/26/2019 12:10:00 AM    True   
428908     7217673  11703089    JC282400  05/26/2019 11:29:00 AM   False   
428909     7217674  11700926    JC279725  05/26/2019 05:13:00 PM   False   
428910     7217675     24560    JC279072  05/26/2019 06:48:00 AM    True   
428911     7217678     24559    JC278908  05/26/2019 02:11:00 AM   False   

        Domestic  Beat  District  Ward  Community Area FBI Code  X Coordinate  \
0          False  1712      17.0  39.0            13.0       06           NaN   
1          False  1233      12.0  25.0            31.0       06           NaN   
2          False  1413      14.0  26.0            22.0       06           NaN   
3          False  2411      24.0  50.0             2.0       14           NaN   
4          False  2433      24.0  48.0            77.0       06           NaN   
...          ...   ...       ...   ...             ...      ...           ...   
428907     False  2522      25.0  36.0            19.0      08B     1145043.0   
428908     False  1921      19.0  47.0             5.0       11           NaN   
428909      True  1011      10.0  24.0            29.0       26     1152126.0   
428910     False  1233      12.0  25.0            28.0      01A     1167752.0   
428911     False  1233      12.0  25.0            28.0      01A     1167746.0   

        Y Coordinate  Year              Updated On   Latitude  Longitude  
0                NaN  2019  03/26/2019 04:15:20 PM        NaN        NaN  
1                NaN  2019  03/26/2019 04:15:20 PM        NaN        NaN  
2                NaN  2019  03/27/2019 04:10:11 PM        NaN        NaN  
3                NaN  2019  03/27/2019 04:10:11 PM        NaN        NaN  
4                NaN  2019  03/27/2019 04:10:11 PM        NaN        NaN  
...              ...   ...                     ...        ...        ...  
428907     1913219.0  2019  06/30/2019 03:56:27 PM  41.917879 -87.742535  
428908           NaN  2019  06/02/2019 04:09:42 PM        NaN        NaN  
428909     1893208.0  2019  06/30/2019 03:56:27 PM  41.862830 -87.717040  
428910     1893853.0  2019  06/20/2020 03:48:45 PM  41.864278 -87.659660  
428911     1893853.0  2019  06/20/2020 03:48:45 PM  41.864278 -87.659682  

[428912 rows x 17 columns]

In [15]:
null_counts = dtTemp.isnull().sum()
null_counts[null_counts>0]

Ward              22
X Coordinate    5620
Y Coordinate    5620
Latitude        5620
Longitude       5620
dtype: int64

In [16]:
dtTemp.dropna(subset = ["Ward"], inplace=True)
dtTemp.dropna(subset = ["X Coordinate"], inplace=True)
null_counts = dtTemp.isnull().sum()
null_counts[null_counts>0]

Series([], dtype: int64)

Now dataset is clean no NaN values

In [17]:
dtTemp.isnull().sum()

Unnamed: 0        0
ID                0
Case Number       0
Date              0
Arrest            0
Domestic          0
Beat              0
District          0
Ward              0
Community Area    0
FBI Code          0
X Coordinate      0
Y Coordinate      0
Year              0
Updated On        0
Latitude          0
Longitude         0
dtype: int64

In [18]:
del dtTemp['ID']
del dtTemp['Year']
del dtTemp['Case Number']
del dtTemp['Updated On']

In [19]:
for date in holidays.UnitedStates(years=2020).items():print(str(date[0]))

2020-01-01
2020-01-20
2020-02-17
2020-05-25
2020-07-04
2020-07-03
2020-09-07
2020-10-12
2020-11-11
2020-11-26
2020-12-25


In [20]:
us_holidays = []
for date in holidays.UnitedStates(years=2019).items():
    us_holidays.append(str(date[0]))
for date in holidays.UnitedStates(years=2020).items():
    us_holidays.append(str(date[0]))
    
print(us_holidays)

['2019-01-01', '2019-01-21', '2019-02-18', '2019-05-27', '2019-07-04', '2019-09-02', '2019-10-14', '2019-11-11', '2019-11-28', '2019-12-25', '2020-01-01', '2020-01-20', '2020-02-17', '2020-05-25', '2020-07-04', '2020-07-03', '2020-09-07', '2020-10-12', '2020-11-11', '2020-11-26', '2020-12-25']


In [21]:
dt0 = dtTemp.copy()
dt0.drop(['ID', 'Case Number', 'Updated On', 'Block', 'IUCR', 'Description', 'Domestic','Arrest', 'Beat', 'Location', 'X Coordinate', 'Y Coordinate', 'Ward', 'FBI Code'], 1, inplace=True)
#dt0["Arrest"] = dt0["Arrest"].astype(int)
#dt0["Domestic"] = dt0["Domestic"].astype(int)
#dt0["FBI Code"] = (DataFrame["FBI Code"]).apply(lambda x: int(x, 16))
dt0["Season"] = (pd.to_datetime(dt0['Date'], format="%m/%d/%Y %I:%M:%S %p").dt.month%12 + 3)//3
dt0["Weekday"] = pd.to_datetime(dt0['Date'], format="%m/%d/%Y %I:%M:%S %p").dt.dayofweek
dt0["Just_Date"] = (pd.to_datetime(dt0['Date'])).dt.date
dt0["Is_Holiday"] = [ 1 if str(val).split()[0] in us_holidays else 0 for val in dt0["Just_Date"]]
dt0["Day_of_Month"] = pd.to_datetime(dt0["Just_Date"]).dt.day
dt0["Month"] = pd.to_datetime(dt0["Just_Date"]).dt.month
dt0["IsDark"]= DataFrame.apply(lambda x: is_dark(x['Date']) ,axis=1)


In [22]:
dt0.columns

Index(['Unnamed: 0', 'Date', 'Arrest', 'Domestic', 'Beat', 'District', 'Ward',
       'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate',
       'Latitude', 'Longitude', 'Season', 'Weekday', 'Just_Date', 'Is_Holiday',
       'Day_of_Month', 'Month', 'IsDark'],
      dtype='object')

In [23]:
dt0

Unnamed: 0                    Date  Arrest  Domestic  Beat  District  \
276          63291  04/10/2019 04:37:00 PM       0         0   511       5.0   
282          63376  04/12/2019 04:08:00 PM       0         1  1731      17.0   
283          63377  04/19/2019 01:57:00 PM       0         1  1532      15.0   
294          63453  04/25/2019 05:20:00 PM       0         1   513       5.0   
353          63857  05/13/2019 05:26:00 PM       0         0  2222      22.0   
...            ...                     ...     ...       ...   ...       ...   
428905     2408049  05/19/2019 05:36:00 AM       0         0  1531      15.0   
428907     7217672  05/26/2019 12:10:00 AM       1         0  2522      25.0   
428909     7217674  05/26/2019 05:13:00 PM       0         1  1011      10.0   
428910     7217675  05/26/2019 06:48:00 AM       1         0  1233      12.0   
428911     7217678  05/26/2019 02:11:00 AM       0         0  1233      12.0   

        Ward  Community Area  FBI Code  X Coordinate  Y Coordinate   Latitude  \
276      9.0            49.0        23     1181051.0     1837225.0  41.708589   
282     30.0            16.0         2     1147835.0     1921408.0  41.940298   
283     28.0            25.0        23     1141669.0     1901165.0  41.884865   
294      9.0            49.0       139     1180832.0     1833222.0  41.697609   
353     21.0            73.0       138     1169908.0     1844927.0  41.729973   
...      ...             ...       ...           ...           ...        ...   
428905  37.0            25.0        26     1143226.0     1906866.0  41.900480   
428907  36.0            19.0       139     1145043.0     1913219.0  41.917879   
428909  24.0            29.0        38     1152126.0     1893208.0  41.862830   
428910  25.0            28.0        26     1167752.0     1893853.0  41.864278   
428911  25.0            28.0        26     1167746.0     1893853.0  41.864278   

        Longitude  Season  Weekday   Just_Date  Is_Holiday  Day_of_Month  \
276    -87.612583       2        2  2019-04-10           0            10   
282    -87.732066       2        4  2019-04-12           0            12   
283    -87.755230       2        4  2019-04-19           0            19   
294    -87.613508       2        3  2019-04-25           0            25   
353    -87.653167       2        0  2019-05-13           0            13   
...           ...     ...      ...         ...         ...           ...   
428905 -87.749370       2        6  2019-05-19           0            19   
428907 -87.742535       2        6  2019-05-26           0            26   
428909 -87.717040       2        6  2019-05-26           0            26   
428910 -87.659660       2        6  2019-05-26           0            26   
428911 -87.659682       2        6  2019-05-26           0            26   

        Month  IsDark  
276         4   False  
282         4   False  
283         4   False  
294         4   False  
353         5   False  
...       ...     ...  
428905      5   False  
428907      5    True  
428909      5   False  
428910      5   False  
428911      5    True  

[423270 rows x 20 columns]

In [24]:
dt0.shape

(423270, 20)

Creating a map from  "Community Area" to map coordinates

In [ ]:
community_area_dict = dict()

for i in range(1,78):
    area_df = DataFrame[DataFrame["Community Area"]==i]
    vc = area_df["Block"].value_counts()
    max_block = vc.head(1).index[0]
    block_df = area_df[area_df["Block"]==max_block]
    var = block_df["Location"].iloc[0]
    count = 1
    while pd.isnull(var):
        var = block_df["Location"].iloc[count]
        count+=1
    community_area_dict[i] = var

In [25]:
dt0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 423270 entries, 276 to 428911
Data columns (total 20 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Unnamed: 0      423270 non-null  int64  
 1   Date            423270 non-null  object 
 2   Arrest          423270 non-null  int32  
 3   Domestic        423270 non-null  int32  
 4   Beat            423270 non-null  int64  
 5   District        423270 non-null  float64
 6   Ward            423270 non-null  float64
 7   Community Area  423270 non-null  float64
 8   FBI Code        423270 non-null  int64  
 9   X Coordinate    423270 non-null  float64
 10  Y Coordinate    423270 non-null  float64
 11  Latitude        423270 non-null  float64
 12  Longitude       423270 non-null  float64
 13  Season          423270 non-null  int64  
 14  Weekday         423270 non-null  int64  
 15  Just_Date       423270 non-null  object 
 16  Is_Holiday      423270 non-null  int64  
 17  Day_of_M

In [26]:
ndf = dt0.groupby(['Is_Holiday', 'Day_of_Month', 'Weekday', 'Season', 'IsDark']).size().reset_index(name='Counts')
ndf

Is_Holiday  Day_of_Month  Weekday  Season  IsDark  Counts
0              0             1        0       2   False     533
1              0             1        0       2    True     240
2              0             1        0       3   False    1137
3              0             1        0       3    True     606
4              0             1        1       4   False     928
...          ...           ...      ...     ...     ...     ...
1017           1            25        2       1    True     298
1018           1            27        0       2   False     494
1019           1            27        0       2    True     252
1020           1            28        3       4   False     235
1021           1            28        3       4    True     268

[1022 rows x 6 columns]

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

In [28]:
X = ndf.drop('Counts', axis = 1)
Y = ndf['Counts']

In [29]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X,Y,test_size=0.2)
classifier= DecisionTreeClassifier()
classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
y_pred = classifier.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         1
         132       0.00      0.00      0.00         0
         133       0.00      0.00      0.00         1
         139       0.00      0.00      0.00         0
         148       0.00      0.00      0.00         1
         150       0.00      0.00      0.00         1
         151       0.00      0.00      0.00         0
         156       0.00      0.00      0.00         0
         167       0.00      0.00      0.00         1
         168       0.00      0.00      0.00         0
         170       0.00      0.00      0.00         1
         174       0.00      0.00      0.00         0
         175       0.00      0.00      0.00         1
         179       0.00      0.00      0.00         3
         183       0.00      0.00      0.00         1
         184       0.00    

C:\Users\bdl011\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bdl011\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Check_Holiday = dt0[dt0["Is_Holiday"]==1]
Check_Holiday

In [ ]:
dt0["Month"].value_counts()

Should we  remove rows related to 6 days at the beginning of September?

In [ ]:
x=np.c_[dt0["FBI Code"]]
y=np.c_[dt0["Day_of_Month"]]
dt0.plot(kind='scatter', x="FBI Code", y='Day_of_Month', alpha=(0.4),figsize=(30,5))
plt.show()

In [ ]:
x=np.c_[dt0["FBI Code"]]
y=np.c_[dt0["Date"]]
dt0.plot(kind='scatter', x="FBI Code", y='Date', alpha=(0.4),figsize=(30,5))
plt.show()

In [ ]:
codt1=dt1[dt1["Date"]==6]
codt1.head(3)

In [ ]:
codt1.plot(kind='scatter',x="X Coordinate", y="Y Coordinate", alpha=(0.4),figsize=(20,20),c="Date", cmap=plt.get_cmap("Blues"), colorbar=True, sharex=False)
plt.legend()

In [ ]:
dt2 = DataFrame.copy()
dt2['Date'] = pd.to_datetime(dt2['Date'], format="%m/%d/%Y %I:%M:%S %p").dt.day_name()
dt2

In [ ]:
dt2["Date"].value_counts()

In [ ]:
DataFrame.shape[0]

In [ ]:
DataFrame.shape[1]

In [ ]:
DataFrame["Community Area"].value_counts()

Community Area no. 25 appears 8722 time in the data set

In [ ]:
DataFrame.Description.value_counts()

In [ ]:
DataFrame["Location Description"].value_counts()

In [ ]:
DataFrame.sort_values(by=["Location Description", "Primary Type"])

In [ ]:
DataFrame[(DataFrame["Primary Type"]=="ASSAULT")&(DataFrame["Location Description"]=="STREET")]

In [ ]:
DataFrame.plot(kind='scatter',x="X Coordinate", y="Y Coordinate", alpha=(0.4),figsize=(50,50),c="Community Area", cmap=plt.get_cmap("jet"), colorbar=True, sharex=False)
plt.legend()

In [ ]:
co.plot(kind='scatter',x="X Coordinate", y="Y Coordinate", alpha=(0.4),figsize=(10,10),c="Community Area", cmap=plt.get_cmap("Blues"), colorbar=True, sharex=False)
plt.legend()

Plot histogram that shows per district the number of total crimes.
Next step would be to create a testing data frame , from 20% of the dataset.
Need to make sure that it would resemble  the distribution of all DataSet

29/10/20 START

In [ ]:
dt0.describe()

In [ ]:
corrMatrix= dt0.corr()
corrMatrix["FBI Code"].sort_values(ascending=True)

29/10/20 What is the most common crime  (6 is the most common crime which is theft)

In [ ]:
dt0["Community Area"].value_counts()

In [ ]:
dt0["FBI Code"].value_counts()

In [ ]:
for6=dt0[dt0["FBI Code"]==6]
for6

In [ ]:
for6["Community Area"].value_counts()

From above area 8 has the highest theft crime. I expected based on below linear regression that 36 area would be the one

In [ ]:
x=np.c_[dt0["FBI Code"]]
y=np.c_[dt0["Community Area"]]
dt0.plot(kind='scatter', x="FBI Code", y='Community Area', alpha=(0.4),figsize=(30,10))
plt.show()

In [ ]:
import sklearn.linear_model
model = sklearn.linear_model.LinearRegression()
model.fit(x, y)

In [ ]:
X_new = [[6]]

In [ ]:
print(model.predict(X_new))

In [ ]:
for36=dt0[dt0["Community Area"]==36]
for36

In [ ]:
for36["FBI Code"].value_counts()

In [ ]:
dt0["FBI Code"].value_counts()

In [ ]:
X_new = [[27]]

In [ ]:
print(model.predict(X_new))

29/10/20 END

In [ ]:
DataFrame["Community Area"].value_counts().plot(kind='bar',figsize=(20,5))

In [ ]:
from sklearn.model_selection import train_test_split
train_frame, test_frame = train_test_split(DataFrame)

In [ ]:
test_frame["Community Area"].value_counts().plot(kind='bar',figsize=(20,5))

In [ ]:
train_frame["Community Area"].value_counts().plot(kind='bar',figsize=(20,5))

In [ ]:
len(train_frame)

In [ ]:
len(test_frame)

Convert "FBI Code" Hexa string to numeric value

In [ ]:
dt1['FBI Code'] = (DataFrame["FBI Code"]).apply(lambda x: int(x, 16))
dt1

In [ ]:
from sklearn import linear_model
from sklearn.utils import shuffle

In [ ]:
dt0=dt0[["Date","Arrest","Domestic","Ward","Community Area","FBI Code"]]
dt0

In [ ]:
dt0.info()

In [ ]:
dt0[(dt0["Date"]=="NaN")]

In [ ]:
predict="FBI Code"
X=np.array(dt0.drop([predict],1))

In [ ]:
type(X)

In [ ]:
Y=np.array(dt0[predict])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [ ]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X,Y,test_size=0.1)

In [ ]:
linear=linear_model.LinearRegression()

In [ ]:
dt0

In [ ]:
def clean_dataset(dt0):
    assert isinstance(dt0, pd.DataFrame), "df needs to be a pd.DataFrame"
    dt0.dropna(inplace=True)
    indices_to_keep = ~dt0.isin([np.nan, np.inf, -np.inf]).any(1)
    return dt0[indices_to_keep].astype(np.float64)

In [ ]:
dt0.dropna()